a = str(input())
b = str(input())
c = str(input())
d = str(input())
e = str(input())
f = str(input())
g = str(input())
h = str(input())
i = str(input())
j = str(input())
print(c)
print(g)
print(i)